sudo: false
language: haxe
haxe:
  - "3.2.0"
  - development
neko: "2.0.0"
matrix:
  allow_failures:
    - haxe: development # Allow development to fail until I have time to investigate.
install:
  - yes | haxelib install hxnodejs
  - yes | haxelib install express
  - yes | haxelib git ufront-mvc https://github.com/ufront/ufront-mvc
  - yes | haxelib install pushstate
  - haxelib list
script:
  - haxe server.hxml
  - haxe client.hxml
  # For now, just compiling the example is all we test.  In Future I might add some unit testing too.
